---
apiVersion: v1
kind: Service
metadata:
  name: space-app-service
spec:
  type: LoadBalancer
  selector:
    app: space-app
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: space-app-deployment
  labels:
    app: space-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: space-app
  template:
    metadata:
      labels:
        app: space-app
    spec:
      containers:
      - name: space-app
        image: us-central1-docker.pkg.dev/GOOGLE_PROJECT/space-app-v2/space-app-v2:latest